version: "3.9"

services:
  livekit:
    image: livekit/livekit-server:latest
    command: --dev
    ports:
      - "7880:7880"
      - "7881:7881"
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      - LIVEKIT_URL=ws://livekit:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MEM0_API_KEY=${MEM0_API_KEY}
      - TOKEN_SERVER_PORT=8000
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python agent.py
    depends_on:
      - livekit

  token-server:
    build: ./backend
    environment:
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python token_server.py
    ports:
      - "8000:8000"
    depends_on:
      - livekit

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - livekit
      - backend